-- ============================================================================
-- Sacred Pathway Driver Hub — Carrier-Sponsored Driver Access
-- 20260526000000_carrier_sponsored_driver_access.sql
-- ----------------------------------------------------------------------------
-- Adds the multi-user foundation so a Carrier can invite real drivers (with
-- their own auth.users login) and sponsor their Basic Driver access. Drivers
-- who are NOT sponsored by an active Carrier fall through to the Basic Driver
-- paywall ($4.99/mo, separate ASC product — wired in a later commit).
--
-- DOES NOT change the existing single-user RLS model on loads, expenses,
-- paystubs, etc. Existing rows stay scoped to profile_id = auth.uid(). The
-- entitlement resolver (TypeScript, lib/entitlement/resolver.ts) decides
-- which user maps to which carrier and what access level they get.
--
-- Rules:
--   • ADDITIVE ONLY — no DROP, no RENAME, no NOT NULL tightening.
--   • Idempotent: IF NOT EXISTS / DROP-AND-RECREATE policies.
--   • iOS untouched. iOS reads neither table.
--   • Invite-code lookup goes through a SECURITY DEFINER function so a
--     prospective driver can validate a code WITHOUT carrier_invites RLS
--     ever leaking the carrier's roster.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. CARRIER_INVITES — short-lived invite codes for drivers
-- ----------------------------------------------------------------------------
--
-- One row per invite the carrier creates. The carrier can hand out:
--   • An invite code (e.g. "DRV-A3F9") for drivers to type into /join
--   • An email-specific invite (sends notification later; row exists today)
--   • A shareable invite link (/join/<invite_code>) for fast onboarding
--
-- A SINGLE invite row supports all three delivery channels because the
-- code itself is what carrier_members links back to.
CREATE TABLE IF NOT EXISTS public.carrier_invites (
  id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  carrier_profile_id   UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  -- Human-readable code typed at /join. Generated by the carrier; uniqueness
  -- enforced. Format suggestion: "DRV-XXXX" (uppercase alphanumeric, 6-12 chars).
  invite_code          TEXT NOT NULL,
  -- Optional: targeted email-specific invite. NULL = open invite (anyone with
  -- the code can join, up to max_uses).
  email                TEXT,
  -- Driver vs admin role this invite grants on acceptance.
  role                 TEXT NOT NULL DEFAULT 'driver'
                       CHECK (role IN ('driver', 'admin')),
  -- Audit
  created_by_user_id   UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at           TIMESTAMPTZ DEFAULT NOW(),
  -- Lifecycle
  expires_at           TIMESTAMPTZ,             -- NULL = no expiry
  revoked_at           TIMESTAMPTZ,             -- carrier can manually revoke
  -- Usage
  max_uses             INTEGER NOT NULL DEFAULT 1
                       CHECK (max_uses >= 1),
  use_count            INTEGER NOT NULL DEFAULT 0
                       CHECK (use_count >= 0),
  notes                TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_carrier_invites_code_unique
  ON public.carrier_invites (invite_code);
CREATE INDEX IF NOT EXISTS idx_carrier_invites_carrier
  ON public.carrier_invites (carrier_profile_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_carrier_invites_email
  ON public.carrier_invites (email) WHERE email IS NOT NULL;

ALTER TABLE public.carrier_invites ENABLE ROW LEVEL SECURITY;

-- Carrier sees + manages own invites. Prospective drivers do NOT have a
-- direct RLS-allowed SELECT — they validate codes via the function below.
DROP POLICY IF EXISTS "carrier owns own invites" ON public.carrier_invites;
CREATE POLICY "carrier owns own invites" ON public.carrier_invites
  FOR ALL
  USING (carrier_profile_id = auth.uid())
  WITH CHECK (carrier_profile_id = auth.uid());

-- ----------------------------------------------------------------------------
-- 2. CARRIER_MEMBERS — active linkage between an auth user and a carrier
-- ----------------------------------------------------------------------------
--
-- One row per (carrier, user) pair. A user can theoretically be sponsored by
-- MULTIPLE carriers (rare but legal — think a part-time driver). The
-- entitlement resolver returns the most-permissive sponsorship.
--
-- status='removed' rows are preserved for audit + so a re-invite has the
-- prior context to fall back on; the resolver only treats status='active'
-- as sponsored.
--
-- linked_driver_id is the OPTIONAL pointer to a row in public.drivers — the
-- carrier-side roster record. When set, paystub history + load assignments
-- written by the carrier flow through to the driver's app via this link.
CREATE TABLE IF NOT EXISTS public.carrier_members (
  id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  carrier_profile_id   UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  user_id              UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  role                 TEXT NOT NULL DEFAULT 'driver'
                       CHECK (role IN ('driver', 'admin')),
  status               TEXT NOT NULL DEFAULT 'active'
                       CHECK (status IN ('active', 'removed')),
  -- Back-reference to the invite the user accepted (audit trail).
  invite_id            UUID REFERENCES public.carrier_invites(id) ON DELETE SET NULL,
  -- Link to the carrier-side drivers row (paystub history, load assignment).
  linked_driver_id     UUID REFERENCES public.drivers(id) ON DELETE SET NULL,
  joined_at            TIMESTAMPTZ DEFAULT NOW(),
  removed_at           TIMESTAMPTZ,
  removed_by_user_id   UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  notes                TEXT
);

-- A user can only have ONE active membership in a given carrier at a time.
-- (Removed memberships can stack as a history.)
CREATE UNIQUE INDEX IF NOT EXISTS idx_carrier_members_active_unique
  ON public.carrier_members (carrier_profile_id, user_id)
  WHERE status = 'active';
CREATE INDEX IF NOT EXISTS idx_carrier_members_user
  ON public.carrier_members (user_id, status);
CREATE INDEX IF NOT EXISTS idx_carrier_members_carrier
  ON public.carrier_members (carrier_profile_id, status);

ALTER TABLE public.carrier_members ENABLE ROW LEVEL SECURITY;

-- Carrier sees + manages all members of their own org.
DROP POLICY IF EXISTS "carrier manages own members" ON public.carrier_members;
CREATE POLICY "carrier manages own members" ON public.carrier_members
  FOR ALL
  USING (carrier_profile_id = auth.uid())
  WITH CHECK (carrier_profile_id = auth.uid());

-- Driver can SEE (read-only) their own membership rows so the resolver can
-- run client-side queries without a service role.
DROP POLICY IF EXISTS "user reads own memberships" ON public.carrier_members;
CREATE POLICY "user reads own memberships" ON public.carrier_members
  FOR SELECT
  USING (user_id = auth.uid());

-- ----------------------------------------------------------------------------
-- 3. ACCEPT-INVITE FUNCTION (SECURITY DEFINER)
-- ----------------------------------------------------------------------------
--
-- A prospective driver knows only the invite_code. They don't have RLS
-- access to carrier_invites (would leak the carrier roster). This function
-- runs as the table owner, validates the code, and either inserts the
-- carrier_members row + bumps use_count, or returns an error string.
--
-- Returns JSON: { ok: bool, error?: text, carrier_profile_id?: uuid,
--                 carrier_member_id?: uuid }
CREATE OR REPLACE FUNCTION public.accept_carrier_invite(p_invite_code TEXT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_user_id      UUID := auth.uid();
  v_invite       public.carrier_invites%ROWTYPE;
  v_existing_id  UUID;
  v_new_member   UUID;
BEGIN
  IF v_user_id IS NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'not_signed_in');
  END IF;

  -- Locate by code (case-sensitive — codes are uppercase by convention).
  SELECT * INTO v_invite
  FROM public.carrier_invites
  WHERE invite_code = p_invite_code;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'error', 'invite_not_found');
  END IF;

  IF v_invite.revoked_at IS NOT NULL THEN
    RETURN jsonb_build_object('ok', false, 'error', 'invite_revoked');
  END IF;

  IF v_invite.expires_at IS NOT NULL AND v_invite.expires_at < NOW() THEN
    RETURN jsonb_build_object('ok', false, 'error', 'invite_expired');
  END IF;

  IF v_invite.use_count >= v_invite.max_uses THEN
    RETURN jsonb_build_object('ok', false, 'error', 'invite_max_uses_reached');
  END IF;

  -- If the invite was email-scoped, only that email may redeem it.
  IF v_invite.email IS NOT NULL THEN
    IF (SELECT email FROM auth.users WHERE id = v_user_id) IS DISTINCT FROM v_invite.email THEN
      RETURN jsonb_build_object('ok', false, 'error', 'invite_email_mismatch');
    END IF;
  END IF;

  -- Already a member? Treat as idempotent success.
  SELECT id INTO v_existing_id
  FROM public.carrier_members
  WHERE carrier_profile_id = v_invite.carrier_profile_id
    AND user_id = v_user_id
    AND status = 'active';

  IF v_existing_id IS NOT NULL THEN
    RETURN jsonb_build_object(
      'ok', true,
      'carrier_profile_id', v_invite.carrier_profile_id,
      'carrier_member_id', v_existing_id,
      'already_member', true
    );
  END IF;

  -- Insert the membership + bump use_count atomically.
  INSERT INTO public.carrier_members (
    carrier_profile_id, user_id, role, status, invite_id
  )
  VALUES (
    v_invite.carrier_profile_id,
    v_user_id,
    v_invite.role,
    'active',
    v_invite.id
  )
  RETURNING id INTO v_new_member;

  UPDATE public.carrier_invites
  SET use_count = use_count + 1
  WHERE id = v_invite.id;

  RETURN jsonb_build_object(
    'ok', true,
    'carrier_profile_id', v_invite.carrier_profile_id,
    'carrier_member_id', v_new_member,
    'already_member', false
  );
END;
$$;

-- Authenticated users can call the function (anon cannot — RLS-equivalent).
REVOKE ALL ON FUNCTION public.accept_carrier_invite(TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.accept_carrier_invite(TEXT) TO authenticated;

-- ----------------------------------------------------------------------------
-- 4. INVITE PREVIEW FUNCTION (SECURITY DEFINER, read-only)
-- ----------------------------------------------------------------------------
--
-- Lets a prospective driver see WHAT carrier is inviting them BEFORE they
-- accept, without leaking the full invite row (no email, no max_uses).
-- Returns only: { ok, carrier_company_name, role, expired, revoked, exhausted }
CREATE OR REPLACE FUNCTION public.preview_carrier_invite(p_invite_code TEXT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_invite       public.carrier_invites%ROWTYPE;
  v_company      TEXT;
BEGIN
  SELECT * INTO v_invite
  FROM public.carrier_invites
  WHERE invite_code = p_invite_code;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('ok', false, 'error', 'invite_not_found');
  END IF;

  SELECT company_name INTO v_company
  FROM public.profiles
  WHERE id = v_invite.carrier_profile_id;

  RETURN jsonb_build_object(
    'ok', true,
    'carrier_company_name', COALESCE(v_company, 'A Carrier'),
    'role', v_invite.role,
    'expired', v_invite.expires_at IS NOT NULL AND v_invite.expires_at < NOW(),
    'revoked', v_invite.revoked_at IS NOT NULL,
    'exhausted', v_invite.use_count >= v_invite.max_uses
  );
END;
$$;

REVOKE ALL ON FUNCTION public.preview_carrier_invite(TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.preview_carrier_invite(TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.preview_carrier_invite(TEXT) TO anon;

-- ----------------------------------------------------------------------------
-- 5. ACCOUNT TYPE HINT on profiles (additive, nullable)
-- ----------------------------------------------------------------------------
--
-- Helps the entitlement resolver short-circuit common cases. NULL means
-- "treat as carrier" (matches every existing profile row — they all came in
-- as carriers via the iOS app). New rows from the driver join flow will be
-- created with account_type='driver'.
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS account_type TEXT
    CHECK (account_type IS NULL OR account_type IN ('carrier', 'driver'));
